name: CDAS Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 mypy black
    
    - name: Format check with black
      run: |
        black --check cdas/ tests/
    
    - name: Lint with flake8
      run: |
        flake8 cdas/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 cdas/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Type check with mypy
      run: |
        mypy cdas/
    
    - name: Run unit tests
      run: |
        pytest tests/test_db/ tests/test_analysis/ tests/test_financial_analysis/ --cov=cdas --cov-report=xml
    
    - name: Run integration tests
      run: |
        pytest tests/test_integration/ --cov=cdas --cov-append --cov-report=xml
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false